services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rainuser
      POSTGRES_PASSWORD: rainpass
      POSTGRES_DB: raindb
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      ConnectionStrings__Default: Host=db;Database=raindb;Username=rainuser;Password=rainpass
    ports:
      - "5000:8080"
    depends_on:
      - db
